name: Build

on:
  push:
    paths-ignore:
      - '.github/*'
      - '.github/*_TEMPLATE/**'
      - '*.md'
  pull_request:
    paths-ignore:
      - '.github/*'
      - '.github/*_TEMPLATE/**'
      - '*.md'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Compile
      run: |
           sudo npm install -g libdragon
           sudo libdragon download
           sudo libdragon start
           sudo libdragon make EP=4
           cp omnispeak/LICENSE LICENSE
           export BUILD_TAG=build-$(date -u +'%Y%m%d%H%M')
           echo "BUILD_TAG=$BUILD_TAG" >> $GITHUB_ENV

    - if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      name: Create Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: ${{ env.BUILD_TAG }}
        prerelease: true
        files: |
               LICENSE
               *.z64
